//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdTest
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Vendor { get; set; }
        public double Price { get; set; }
        public double Discount { get; set; }
        public string Image { get; set; }
        public int Count { get; set; }
        public double PriceWDis
        {
            get
            {
                return Price-((Price/100)*Discount);
            }
        }
        public string ImgPath
        {
            get
            {
                if (Count != 0)
                {
                    return "/img/" + Image + ".jpeg";
                }
                else
                {
                    return "/img/no.jpg";
                }
                
            }
        }
        public string Color
        {
            get
            {
                if (Discount >= 15)
                {
                    return "#aa1359";
                }
                else
                {
                    return "#ffffff";
                }
            }
        }
    }
}
